name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run build --if-present

    - name: Set up OpenTelemetry
      run: |
        npm install @opentelemetry/api @opentelemetry/sdk-trace-node @opentelemetry/instrumentation @opentelemetry/instrumentation-http @opentelemetry/exporter-trace-otlp-http
        node otel-setup.js

    - name: Run integration tests
      run: npm run integration-test

    - name: Collect and analyze traces
      run: |
        curl -X GET http://localhost:16686/api/traces?service=github-actions-ci
        

    - name: Collect and analyze metrics
      run: |
        curl -X GET http://localhost:9090/api/v1/query?query=nodejs_http_requests_total
       